version: '3'

services:
  db:
    image: postgres:13
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notepad
  app:
    build: .
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notepad
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8001:8001"
    restart: on-failure
    depends_on:
      - db
